// Accuracy check
// --------------
// The rush/pass/sack fumble bug lived for two weeks with 31 suites, a
// fuzzer and 93 NFL games running over it. It was not a coverage gap:
// ui_driver.js drives all three fumble toggles, and coverage_probe.js
// walked the path on every run. The bug survived because the probe
// REPORTS and nothing ASSERTS -- the play count was printed on every run
// and read by no one.
//
// So this file does not add coverage. It adds judgement to coverage that
// already exists, in two layers that fail for different reasons:
//
//   INVARIANTS  Absolute rules that must hold whatever the code does.
//               These catch a number that has been wrong since the day
//               it was written, which a snapshot never can.
//
//   GOLDEN      A frozen fingerprint of every path's output. This catches
//               UNINTENDED CHANGE -- any number that moves without
//               somebody meaning it to.
//
// The distinction matters. A golden file blesses whatever the code does
// today: generate it against a bug and it will defend that bug forever.
// That is exactly why the invariants exist, and why `--update` prints a
// diff and makes you look at it rather than quietly rewriting.
//
//   node tests/accuracy_check.js            # check
//   node tests/accuracy_check.js --update   # re-bless, after reading the diff

const fs = require('fs');
const path = require('path');
const { run, summariseStats } = require('./coverage_probe');

const GOLDEN = path.join(__dirname, 'accuracy.golden.json');
const UPDATE = process.argv.includes('--update');

// Entries that legitimately write more than one play. The guided
// start-of-game flow writes the kick before anyone knows where the ball
// came down, so the outcome arrives separately -- see the touchback
// compatibility path in engine.js. ANYTHING ELSE writing two plays for
// one entry is the bug this file was written for: keep this list short
// and make each addition argue for itself.
const MULTI_PLAY_OK = new Set([]);

const ORD = { '1st': 1, '2nd': 2, '3rd': 3, '4th': 4 };

// ---------------------------------------------------------------------
// Fingerprint: everything downstream reads roles and effect, so freezing
// those freezes the stats too, without this file needing its own copy of
// the box score.
// ---------------------------------------------------------------------
function fingerprint(rec) {
  const entry = (rec.plays || []).filter(p => p.roles);
  const sig = (p) => {
    const r = p.roles || {}, e = p.effect || {};
    const roleBits = Object.keys(r).sort().map(k => {
      const v = r[k];
      if (v && typeof v === 'object') {
        return k + '{' + Object.keys(v).sort().map(j => j + '=' + v[j]).join(',') + '}';
      }
      return k + '=' + v;
    });
    const effBits = Object.keys(e).sort().map(k => {
      const v = e[k];
      return k + '=' + (v && typeof v === 'object' ? JSON.stringify(v) : v);
    });
    return { text: p.text, roles: roleBits, effect: effBits };
  };
  const st = (s) => s ? [s.possession, s.down, s.distance, s.fieldPos,
    s.scores && (s.scores.teamA + '-' + s.scores.teamB)].join('|') : null;
  return {
    saved: !!rec.saved,
    reason: rec.reason || null,
    error: rec.error || null,
    entryPlays: entry.length,
    plays: entry.map(sig),
    before: st(rec.before),
    after: st(rec.after),
    // The printed numbers, not only the roles they are derived from.
    box: rec.box ? summariseStats(rec.box) : null,
  };
}

// ---------------------------------------------------------------------
// Invariants
// ---------------------------------------------------------------------
function invariants(rec) {
  const out = [];
  const fail = (rule, detail) => out.push({ rule, detail });
  if (rec.error) return out;               // the probe already reports these
  if (!rec.saved) return out;

  const entry = (rec.plays || []).filter(p => p.roles);

  // I1. ONE ENTRY, ONE PLAY.
  // The fumble bug in one line. A scorer pressed Review once; anything
  // that writes two plays has invented a snap, and every per-play number
  // downstream -- down attempts, play counts, drive length -- inherits it.
  if (entry.length > 1 && !MULTI_PLAY_OK.has(rec.name)) {
    fail('one entry writes one play',
      entry.length + ' plays written: ' + entry.map(p => JSON.stringify(p.text)).join(' + '));
  }

  // I2. THE LOG TEXT AND THE STATE MACHINE MUST AGREE.
  // The text is generated by parseInput and the down is advanced by
  // computeState -- two separate pieces of code that must reach the same
  // answer. When the fumble was split, the text said "3rd & 11" about a
  // down that only existed because a play had been invented, so the two
  // agreed with each other and both were wrong. They now agree and are
  // both right; this catches the case where they drift apart, which is
  // the ordinary way a down bug shows up.
  const dd = (rec.text || '').match(/—\s*(1st|2nd|3rd|4th)\s*&\s*(\d+|goal)/i);
  if (dd && rec.after && rec.after.down !== null) {
    const wantDown = ORD[dd[1].toLowerCase()];
    const wantDist = dd[2].toLowerCase() === 'goal' ? null : parseInt(dd[2], 10);
    if (wantDown !== rec.after.down) {
      fail('log text down matches computed down',
        'text says ' + dd[1] + ', state says ' + rec.after.down);
    }
    if (wantDist !== null && rec.after.distance !== null && wantDist !== rec.after.distance) {
      fail('log text distance matches computed distance',
        'text says ' + wantDist + ', state says ' + rec.after.distance);
    }
  }

  // I3. A CHANGE OF POSSESSION CANNOT ALSO ADVANCE THE OLD OFFENSE'S DOWN.
  // The team taking over starts a series. If possession moved and the
  // down is neither 1 nor cleared, something advanced a down for a team
  // that no longer has the ball.
  if (rec.before && rec.after && rec.before.possession && rec.after.possession &&
      rec.before.possession !== rec.after.possession &&
      rec.after.down !== null && rec.after.down !== 1) {
    fail('possession change starts a new series',
      'possession ' + rec.before.possession + ' -> ' + rec.after.possession +
      ' but down is ' + rec.after.down);
  }

  // I4. A SAVED PLAY CARRIES A PLAY TYPE.
  // Everything downstream buckets on roles.playType. A play saved without
  // one is invisible to the box score while still occupying the log --
  // which reads as "the stat is missing" and gets chased in the wrong file.
  entry.forEach((p, i) => {
    if (!p.roles.playType) {
      fail('every saved play has a playType',
        'play ' + (i + 1) + ' (' + JSON.stringify(p.text) + ') has none');
    }
  });

  return out;
}

function diffGolden(oldF, newF) {
  const lines = [];
  const walk = (a, b, p) => {
    const ja = JSON.stringify(a), jb = JSON.stringify(b);
    if (ja === jb) return;
    if (a && b && typeof a === 'object' && typeof b === 'object' && !Array.isArray(a)) {
      for (const k of new Set([...Object.keys(a), ...Object.keys(b)])) walk(a[k], b[k], p + '.' + k);
      return;
    }
    lines.push('      ' + p.replace(/^\./, '') + ':\n        was: ' + ja + '\n        now: ' + jb);
  };
  walk(oldF, newF, '');
  return lines;
}

run().then(rows => {
  const now = {};
  const problems = [];
  let invFails = 0;

  for (const rec of rows) {
    now[rec.name] = fingerprint(rec);
    const bad = invariants(rec);
    if (bad.length) {
      invFails += bad.length;
      problems.push({ name: rec.name, bad });
    }
  }

  console.log('=== Accuracy check ===\n');
  console.log('Paths exercised: ' + rows.length + '\n');

  console.log('--- Invariants ---');
  if (!problems.length) {
    console.log('  ok  all ' + rows.length + ' paths hold every invariant\n');
  } else {
    for (const p of problems) {
      console.log('  XX  ' + p.name);
      p.bad.forEach(b => console.log('        ' + b.rule + '\n          ' + b.detail));
    }
    console.log('');
  }

  let goldFails = 0;
  console.log('--- Golden snapshot ---');
  if (!fs.existsSync(GOLDEN)) {
    fs.writeFileSync(GOLDEN, JSON.stringify(now, null, 2) + '\n');
    console.log('  No golden file. Written ' + Object.keys(now).length + ' paths to ' +
      path.basename(GOLDEN) + '.\n  READ IT before committing: it is now the definition of correct.\n');
  } else {
    const was = JSON.parse(fs.readFileSync(GOLDEN, 'utf8'));
    const names = new Set([...Object.keys(was), ...Object.keys(now)]);
    const changed = [];
    for (const n of names) {
      if (!(n in was)) { changed.push('  ++  ' + n + ' (new path)'); continue; }
      if (!(n in now)) { changed.push('  --  ' + n + ' (path gone)'); continue; }
      const d = diffGolden(was[n], now[n]);
      if (d.length) changed.push('  XX  ' + n + '\n' + d.join('\n'));
    }
    if (!changed.length) {
      console.log('  ok  all ' + Object.keys(now).length + ' paths match the golden file\n');
    } else {
      goldFails = changed.length;
      changed.forEach(c => console.log(c));
      console.log('\n  ' + changed.length + ' path(s) changed.');
      console.log('  If every change above is intended, re-bless with --update.\n');
      if (UPDATE) {
        fs.writeFileSync(GOLDEN, JSON.stringify(now, null, 2) + '\n');
        console.log('  --update given: golden rewritten.\n');
        goldFails = 0;
      }
    }
  }

  const total = invFails + goldFails;
  console.log('Failures: ' + total);
  if (!total) console.log('  every path holds, and nothing moved that nobody moved.');
  process.exit(total ? 1 : 0);
}).catch(e => {
  console.error('accuracy_check could not run:', e && e.stack || e);
  process.exit(1);
});
