// Stat identities, the engine's own oracle, and nothing-missed
// =============================================================
//   node tests/stat_identity_fuzz_check.js            # 25 games
//   node tests/stat_identity_fuzz_check.js 80 555 50  # games, seed, plays
//
// Written 31 Aug 2026, when Andy asked for proof the stats are right
// before schools arrive. fuzz_check.js already fuzzes hard, but its
// box-score assertions are per-PLAYER sanity. The identities that hold a
// stat sheet together are cross-cutting, and nothing asserted them over
// generated games.
//
// PROVEN TO HAVE TEETH by mutation: three faults were injected into
// engine.js and all three were caught in 3 of 3 games --
//   * a completed pass crediting the receiver one yard short
//   * a catch not counted for the receiver
//   * every rush credited to the other team
// A check that has never failed has not been shown to work.
// THE FUZZ RUN. Generates games through the real UI, then applies the
// cross-cutting identities, the engine's own independent oracle, and the
// nothing-is-missed check to each one.
//
//   node statsfuzz.js [games] [seed] [playsPerGame]
const fs = require('fs');
const path = require('path');
const { bootGamePage, bootPage } = require('./harness');
const { enterPlay, setDrive } = require('./ui_driver');
// THE IDENTITIES A STAT SHEET MUST SATISFY, ON FUZZED GAMES.
// =====================================================================
// Andy, 31 Aug 2026, with schools signing up: prove the stats compute
// correctly, land on the right team and player, and that nothing is
// quietly dropped.
//
// tests/fuzz_check.js already fuzzes hard, but its box-score checks are
// per-PLAYER sanity (no negative attempts, completions <= attempts). The
// identities that actually hold a stat sheet together are CROSS-CUTTING
// -- they relate one category to another -- and nothing asserted them
// over generated games:
//
//   passing yards      == receiving yards        (per team)
//   completions        == receptions             (per team)
//   points from scores == the scoreboard         (per team)
//   every credited play lands on exactly one team
//   no player is credited to both teams
//   every play with roles moves at least one number, or is on a
//     declared no-stat list -- this is the "nothing is missed" check
//
// help.html tells scorers to check the first of those by eye. If it can
// be checked by eye it can be checked here, thousands of times.
//
// Plays are generated by reusing tests/fuzz_check.js's own generator and
// entered through the REAL UI, so parseInput is exercised rather than
// bypassed -- a fixture built by hand would only prove the parts of the
// app I thought to write down.


// tests/fuzz_check.js does not export its generator, so it is read out of
// the module by source. Copying the generator here would mean fuzzing a
// different app than the suite does.
const FSRC = fs.readFileSync(path.join(__dirname, 'fuzz_check.js'), 'utf8');
function lift(name){
  const start = FSRC.indexOf('function ' + name + '(');
  if (start < 0) throw new Error('cannot find ' + name + ' in fuzz_check.js');
  let i = FSRC.indexOf('{', start), depth = 0;
  for (; i < FSRC.length; i++){
    if (FSRC[i] === '{') depth++;
    else if (FSRC[i] === '}'){ depth--; if (!depth) break; }
  }
  return FSRC.slice(start, i + 1);
}
// The generator reads two module-level roster arrays as well; lifted by
// source with everything else so this fuzzes the same players the suite
// does rather than a set invented here.
function liftConst(name){
  const m = new RegExp('^const ' + name + ' = \\[[^\\]]*\\];', 'm').exec(FSRC);
  if (!m) throw new Error('cannot find const ' + name);
  return m[0];
}
const gen = new Function(
  liftConst('OFFENSE') + '\n' + liftConst('DEFENSE') + '\n' +
  lift('rng') + '\n' + lift('pick') + '\n' + lift('int') + '\n' +
  lift('randomPlay') + '\nreturn { rng, randomPlay, int };')();

const N = (x) => Number(x || 0);

// ---- the identities -------------------------------------------------
function identities(box, state){
  const bad = [];
  for (const team of ['teamA', 'teamB']){
    const b = box[team]; if (!b) continue;
    const sum = (cat, f) => Object.values(b[cat] || {}).reduce((t, r) => t + N(r[f]), 0);

    // THE ONE ON THE STAT SHEET. Every completed pass credits a receiver
    // -- "Unknown" when the scorer did not name one -- so the two totals
    // are the same number counted twice. If they ever differ, a catch
    // was credited to nobody or to two people.
    const passYds = sum('passing', 'yds'), recYds = sum('receiving', 'yds');
    if (passYds !== recYds){
      bad.push(team + ': passing yards ' + passYds + ' but receiving yards ' + recYds);
    }
    const comp = sum('passing', 'comp'), rec = sum('receiving', 'rec');
    if (comp !== rec){
      bad.push(team + ': ' + comp + ' completions but ' + rec + ' receptions');
    }
    // A target cannot be recorded without an attempt behind it.
    const att = sum('passing', 'att'), tgt = sum('receiving', 'tgt');
    if (tgt > att){
      bad.push(team + ': ' + tgt + ' targets from only ' + att + ' attempts');
    }
    // Touchdowns are counted in two places and must agree.
    const passTD = sum('passing', 'td'), recTD = sum('receiving', 'td');
    if (passTD !== recTD){
      bad.push(team + ': ' + passTD + ' passing TDs but ' + recTD + ' receiving TDs');
    }
  }

  // NO PLAYER ON BOTH SIDES. A name in both box scores means a jersey
  // number resolved against the wrong roster -- the exact fault that
  // sends a rushing total to the opponent.
  const namesOf = (team) => {
    const s = new Set();
    ['rushing','passing','receiving','defense','specialTeams'].forEach(cat =>
      Object.keys((box[team] || {})[cat] || {}).forEach(k => s.add(k)));
    return s;
  };
  const a = namesOf('teamA'), b2 = namesOf('teamB');
  [...a].filter(x => b2.has(x))
        // A bare "TEAM" line is legitimately on both sides, and so is an
        // unnamed credit.
        .filter(x => !/^TEAM$/i.test(x) && !/^Unknown$/i.test(x))
        .forEach(x => bad.push('"' + x + '" is credited to BOTH teams'));
  return bad;
}

// ---- nothing is missed ----------------------------------------------
// A saved play that moves no number at all is either a play type with no
// statistic (a timeout, a penalty, a marker) or a dropped credit. The
// second is invisible without this: the log looks right and the stat
// sheet is quietly short.
const NO_STAT_PLAYTYPES = new Set([
  'timeout', 'penalty', 'quarter', 'divider', 'adjust', 'clock',
  'flip', 'marker', 'note', 'startClock', 'endClock',
]);
function missedPlays(rows, boxBefore, boxAfter){
  const flat = (box) => {
    const out = {};
    ['teamA','teamB'].forEach(t =>
      ['rushing','passing','receiving','defense','specialTeams'].forEach(cat =>
        Object.entries((box[t] || {})[cat] || {}).forEach(([who, line]) =>
          Object.entries(line).forEach(([f, v]) => { out[t+'|'+cat+'|'+who+'|'+f] = N(v); }))));
    return out;
  };
  const A = flat(boxBefore), B = flat(boxAfter);
  const keys = new Set(Object.keys(A).concat(Object.keys(B)));
  for (const k of keys) if (N(A[k]) !== N(B[k])) return null;   // something moved
  return 'moved no statistic at all';
}




async function oneGame(seed, playsPerGame){
  const rand = gen.rng(seed);
  const findings = [];
  const h = await bootGamePage();
  setDrive(h, { down: 1, distance: 10, side: 'own', yardline: gen.int(rand, 20, 40) });

  let entered = 0;
  // Box score after every play, so a play that moves nothing can be
  // named -- a total taken only at the end cannot say WHICH play was
  // dropped.
  let prevBox = JSON.parse(h.evalIn('JSON.stringify(computeBoxScore(plays))'));
  let prevRows = h.db.plays.length;

  for (let i = 0; i < playsPerGame; i++){
    const before = JSON.parse(h.evalIn('JSON.stringify(computeState())'));
    if (before.fieldPos === null || before.down === null){
      setDrive(h, { down: 1, distance: 10, side: 'own', yardline: gen.int(rand, 20, 40) });
      continue;
    }
    const spec = gen.randomPlay(rand, before);
    try { enterPlay(h, spec); } catch (e){ continue; }
    if (h.db.plays.length === prevRows) continue;      // nothing saved
    entered++;

    const box = JSON.parse(h.evalIn('JSON.stringify(computeBoxScore(plays))'));
    const state = JSON.parse(h.evalIn('JSON.stringify(computeState())'));

    identities(box, state).forEach(d =>
      findings.push({ kind: 'identity', detail: d + '   (after ' + spec.type + ')' }));

    // NOTHING MISSED, per play.
    const saved = h.db.plays.slice(prevRows);
    const pt = saved.map(r => (r.roles && r.roles.playType) || '').join(',');
    const isMarker = saved.every(r => !r.roles || !r.roles.playType ||
                                      NO_STAT_PLAYTYPES.has(r.roles.playType));
    if (!isMarker){
      const missed = missedPlays(saved, prevBox, box);
      if (missed) findings.push({ kind: 'missed',
        detail: 'playType "' + pt + '" (' + spec.type + ') ' + missed });
    }
    prevBox = box; prevRows = h.db.plays.length;
    if (findings.length > 8) break;
  }

  const rows = h.db.plays.map((r, i) =>
    Object.assign({}, r, { sequence_number: r.sequence_number || i + 1 }));
  h.close();

  // THE ENGINE'S OWN ORACLE, on the saved rows. auditBoxScore counts the
  // same plays a second time straight off `roles`; compareBoxScores
  // reports every disagreement. This is the strongest check available --
  // two implementations, one dataset.
  const v = await bootPage('view.html', { existingPlays: rows });
  const box = JSON.parse(v.evalIn('JSON.stringify(computeBoxScore(plays))'));
  const disagree = JSON.parse(v.evalIn(
    'JSON.stringify(typeof compareBoxScores === "function" ? compareBoxScores(plays, computeBoxScore(plays)) : ["compareBoxScores is not loaded"])'));
  const state = JSON.parse(v.evalIn('JSON.stringify(computeState(plays))'));
  v.close();

  disagree.forEach(d => findings.push({ kind: 'oracle', detail: d }));
  identities(box, state).forEach(d => findings.push({ kind: 'identity (final)', detail: d }));

  return { seed, findings, entered, rows: rows.length };
}

(async () => {
  const games = parseInt(process.argv[2], 10) || 25;
  const base  = parseInt(process.argv[3], 10) || 1;
  const per   = parseInt(process.argv[4], 10) || 40;
  const all = [];
  for (let g = 0; g < games; g++){
    const r = await oneGame(base + g * 7919, per);
    all.push(r);
    if ((g + 1) % 10 === 0) console.log('   ...' + (g + 1) + '/' + games + ' games');
  }
  const bad = all.filter(r => r.findings.length);
  const plays = all.reduce((t, r) => t + r.entered, 0);
  console.log('\n=== stat identities, oracle, and nothing-missed ===');
  console.log('games ' + all.length + '   plays entered ' + plays +
              '   rows saved ' + all.reduce((t,r)=>t+r.rows,0));
  console.log('games with findings: ' + bad.length);
  const byKind = {};
  bad.forEach(r => r.findings.forEach(f => {
    byKind[f.kind] = byKind[f.kind] || [];
    if (byKind[f.kind].length < 6) byKind[f.kind].push('seed ' + r.seed + ': ' + f.detail);
  }));
  Object.entries(byKind).forEach(([k, v]) => {
    console.log('\n-- ' + k + ' --');
    v.forEach(d => console.log('   ' + d));
  });
  if (!bad.length) console.log('\nno findings.');
  process.exit(bad.length ? 1 : 0);
})();
